### ISSUE TITLE
Current index

### ISSUE THREAD

**Issue by hog-seruj** [bqworks/accordion-slider-js#2]
Is it possible to get the current index after the move the page?

**Comment by hog-seruj** [comment]
I don't use autoplay and I need to open nextPanel() after scroll page.

**Comment by hog-seruj** [comment]
Looks like I found a way to resolve my task.
`        accordionSlider.addEventListener('pageScroll', (event) => {
          const currentPage = accordionSlider.getCurrentPage();
          const openIndex = currentPage * accordionSlider.getVisiblePanels();
          accordionSlider.openPanel(openIndex + 1);
        });`

**Comment by davidghi** [comment]
Glad you've worked it out and thanks for sharing the solution! By the way, you can also get the current page from the `event` object: `event.detail.index`.
